# syntax=docker/dockerfile:1.7
FROM node@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32 AS build

WORKDIR /console
COPY console/package.json console/package-lock.json ./
RUN npm ci --ignore-scripts
COPY console ./
RUN npm run build

FROM nginx@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10

COPY console/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /console/dist /usr/share/nginx/html
RUN chown -R nginx:nginx /usr/share/nginx/html

USER nginx
EXPOSE 8080
