"""Private MinIO object storage and bounded streaming upload support."""

from __future__ import annotations

import asyncio
import hashlib
import io
import json
from collections.abc import Awaitable, Callable
from typing import Any, BinaryIO

from minio import Minio
from minio.commonconfig import CopySource

from documind.domain.errors import UploadTooLargeError

_MIN_MULTIPART_SIZE = 5 * 1024 * 1024


class _BoundedHashingReader:
    """File-like wrapper that hashes bytes and rejects reads past a hard cap."""

    def __init__(self, reader: BinaryIO, hard_cap_bytes: int) -> None:
        self._reader = reader
        self._hard_cap_bytes = hard_cap_bytes
        self._sha256 = hashlib.sha256()
        self.byte_size = 0

    @property
    def hexdigest(self) -> str:
        return self._sha256.hexdigest()

    def read(self, size: int = -1) -> bytes:
        # Never ask an untrusted reader for an unbounded amount at once.
        bounded_size = min(size, _MIN_MULTIPART_SIZE) if size >= 0 else _MIN_MULTIPART_SIZE
        chunk = self._reader.read(bounded_size)
        if not chunk:
            return b""
        self.byte_size += len(chunk)
        if self.byte_size > self._hard_cap_bytes:
            raise UploadTooLargeError()
        self._sha256.update(chunk)
        return chunk


class StorageService:
    """Async facade over the synchronous MinIO SDK.

    All object names are generated by domain code from UUIDs/checksums. User
    filenames never enter a key.
    """

    def __init__(
        self,
        client: object,
        *,
        bucket_name: str,
        hard_cap_bytes: int,
        run_sync: Callable[..., Awaitable[Any]] = asyncio.to_thread,
    ) -> None:
        self._client = client
        self.bucket_name = bucket_name
        self.hard_cap_bytes = hard_cap_bytes
        self._run_sync = run_sync

    @classmethod
    def from_resolved_credentials(
        cls,
        *,
        endpoint: str,
        access_key: str,
        secret_key: str,
        secure: bool,
        bucket_name: str,
        hard_cap_bytes: int,
    ) -> StorageService:
        """Build an adapter after the composition root resolves OpenBao refs."""
        return cls(
            Minio(endpoint, access_key=access_key, secret_key=secret_key, secure=secure),
            bucket_name=bucket_name,
            hard_cap_bytes=hard_cap_bytes,
        )

    async def initialize(self) -> None:
        """Create the private bucket with object-lock support when absent."""
        exists = await self._run_sync(self._client.bucket_exists, self.bucket_name)  # type: ignore[attr-defined]
        if not exists:
            await self._run_sync(  # type: ignore[attr-defined]
                self._client.make_bucket,
                self.bucket_name,
                object_lock=True,
            )

    async def stream_upload(self, reader: BinaryIO, quarantine_key: str) -> tuple[str, int]:
        """Stream once to quarantine while calculating SHA-256 and byte size."""
        bounded_reader = _BoundedHashingReader(reader, self.hard_cap_bytes)
        try:
            await self._run_sync(  # type: ignore[attr-defined]
                self._client.put_object,
                self.bucket_name,
                quarantine_key,
                bounded_reader,
                length=-1,
                part_size=_MIN_MULTIPART_SIZE,
                content_type="application/octet-stream",
            )
        except Exception:
            # MinIO normally aborts a failed multipart operation. This removal
            # also cleans up clients/fakes that materialized a partial object.
            await self.remove_object(quarantine_key, ignore_missing=True)
            raise
        return bounded_reader.hexdigest, bounded_reader.byte_size

    async def move_to_accepted(self, quarantine_key: str, accepted_key: str) -> None:
        """Server-side copy an inspected object, then remove quarantine bytes."""
        source = CopySource(self.bucket_name, quarantine_key)
        await self._run_sync(  # type: ignore[attr-defined]
            self._client.copy_object,
            self.bucket_name,
            accepted_key,
            source,
        )
        await self.remove_object(quarantine_key)

    async def read_bytes(self, object_key: str) -> bytes:
        """Read one private object without exposing an SDK response upstream."""
        return await self._run_sync(self._read_bytes_sync, object_key)

    def _read_bytes_sync(self, object_key: str) -> bytes:
        response = self._client.get_object(self.bucket_name, object_key)  # type: ignore[attr-defined]
        try:
            return response.read()
        finally:
            response.close()
            response.release_conn()

    async def put_json(self, object_key: str, payload: dict[str, Any]) -> None:
        """Persist a canonical derived JSON document under its deterministic key."""
        encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
        await self._run_sync(  # type: ignore[attr-defined]
            self._client.put_object,
            self.bucket_name,
            object_key,
            io.BytesIO(encoded),
            length=len(encoded),
            content_type="application/json",
        )

    async def write_normalized(
        self,
        version_id: object,
        normalization_revision: str,
        payload: dict[str, Any],
    ) -> str:
        """Store an immutable normalized representation and return its key."""
        object_key = self.normalized_key(version_id, normalization_revision)
        await self.put_json(object_key, payload)
        return object_key

    async def remove_object(self, object_key: str, *, ignore_missing: bool = False) -> None:
        """Remove one deterministic private object key."""
        try:
            await self._run_sync(  # type: ignore[attr-defined]
                self._client.remove_object,
                self.bucket_name,
                object_key,
            )
        except Exception:
            if not ignore_missing:
                raise

    @staticmethod
    def quarantine_key(version_id: object) -> str:
        return f"quarantine/{version_id}/original"

    @staticmethod
    def accepted_key(document_id: object, version_number: int, content_sha256: str) -> str:
        return f"originals/{document_id}/{version_number}/{content_sha256}"

    @staticmethod
    def normalized_key(version_id: object, normalization_revision: str) -> str:
        return f"derived/{version_id}/normalized/{normalization_revision}.json"

    @staticmethod
    def evidence_key(version_id: object, stage: str, attempt: int) -> str:
        return f"evidence/{version_id}/{stage}/{attempt}.json"

    @staticmethod
    def sealed_key(version_id: object, seal_revision: str) -> str:
        """Return the deterministic key for a sealed audit anchor."""
        return f"sealed/{version_id}/{seal_revision}.json"

    async def write_evidence(
        self,
        version_id: object,
        stage: str,
        attempt: int,
        payload: dict[str, Any],
    ) -> str:
        """Persist evidence for a stage attempt and return its immutable key."""
        key = self.evidence_key(version_id, stage, attempt)
        await self.put_json(key, payload)
        return key

    async def write_sealed(
        self,
        version_id: object,
        seal_revision: str,
        payload: dict[str, Any],
    ) -> str:
        """Persist a sealed audit anchor and return its immutable key."""
        key = self.sealed_key(version_id, seal_revision)
        await self.put_json(key, payload)
        return key
